name:                rupaka
version:             0.1.0.0
github:              "githubuser/rupaka"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rupaka#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
    - template-haskell
    - text
    - parsec
    - containers
    - file-embed
    - bytestring
    - aeson
    - optparse-applicative
    - regex-tdfa
    - regex-base
    - split
    - hslogger
    - directory

executables:
  rupaka-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rupaka
    - template-haskell
    - text
    - parsec
    - containers
    - file-embed
    - bytestring
    - aeson
    - optparse-applicative
    - regex-tdfa
    - regex-base
    - split
    - hslogger
    - directory

tests:
  rupaka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rupaka
